apiVersion: v1
kind: Secret
metadata:
  name: memos-db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "Skills1234!"
  MEMOS_DSN: "postgresql://memos:PDxNNAwub6M8atcyPWxBfQzKlu84fOSj@postgres-service.database.svc.cluster.local:5432/memos?sslmode=disable"
